baseURL = "https://rahulwa.com/"
languageCode = "en-us"
title = "Rahul Sinha"
theme = "paperback"
googleAnalytics = "UA-105014915-1"
disqusShortname = "rahulwa"

[params]
AuthorName = "Rahul Sinha"
HomepagePosts = 10
GithubUsername = "rahulwa"
TwitterUsername = "rahulwa_"